name: Issue to Pull Request
on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-pr:
    if: startsWith(github.event.issue.title, '[Package]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Info
        id: vars
        run: |
          # On récupère le nom après "[Package]: "
          PKG=$(echo "${{ github.event.issue.title }}" | sed 's/\[Package\]: //g' | xargs)
          # On remplace les espaces par des tirets pour la branche
          CLEAN_PKG=$(echo "$PKG" | tr ' ' '-')
          echo "pkg_name=$CLEAN_PKG" >> $GITHUB_OUTPUT

      - name: Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "add-${{ steps.vars.outputs.pkg_name }}"
          echo "Submission for ${{ steps.vars.outputs.pkg_name }}" > "packages/${{ steps.vars.outputs.pkg_name }}.txt"
          git add .
          git commit -m "Add ${{ steps.vars.outputs.pkg_name }}"
          git push origin "add-${{ steps.vars.outputs.pkg_name }}"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Add ${{ steps.vars.outputs.pkg_name }}" \
            --body "Closes #${{ github.event.issue.number }}. Automatic PR." \
            --base main \
            --head "add-${{ steps.vars.outputs.pkg_name }}"
